// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- generated by the OpenNext build
// @ts-ignore Generated by the OpenNext build.
import handler from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,
  scheduled(_event, env, ctx) {
    const request = new Request(new URL("/api/cron/sync", env.NEXT_PUBLIC_APP_URL), {
      headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(handler.fetch(request, env, ctx));
  },
} satisfies ExportedHandler<CloudflareEnv>;
